---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-05-08T17:00:47.25493514Z"
  name: instavote
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/ADRH10/instavote.git
